easy={'digress':'to deviate or wander away from the main topic',
'forward':'a direction not in front of you',
'habitat':'a type of natural home',
'current':'not past or future',
'episode':'a single from a series',
'pattern':'a decorative design',
'dribble':'think basketball',
'develop':'to create',
'persist':'you can do it - don\'t give up!',
'edition':'a version of a literary work',
'cluster':'a group close together',
'partner':'you need one of these for a ballroom dance competition',
'recycle':'->,reduce, reuse...and close the loop for our planet',
'quarter':'not a dime and definitely not a silver dollar',
'climate':'weather conditions of a region'}

hard={'quotation':'something often repeated from a famous speech',
'deviation':'the opposite of conformity',
'landowner':'owner of a territory',
'pollution':'a form of contamination',
'situation':'famous member of Jersey Shore oR a state of affairs',
'rebellion':'an uprising',
'translate':'to restate in another language',
'staircase':'links a first floor to a second floor',
'transport':'to take or carry something from one place to another',
'parameter':'variable found inside parentheses in a function def in python',
'adventure':'an exciting journey',
'explosion':'what happens when you light C4',
'volunteer':'a person who donates time freely for a cause or task',
'essential':'vital, very important',
'precision':'the condition of being exact and accurate'}
